### ISSUE TITLE
running with a hosted model?

### ISSUE THREAD

**Issue by dcsan** [jparkerweb/semantic-chunking#5]
i'd like to include this technique in a larger project but I'm worried about the requirements downloading the model as I'm using a containerized environment.

what would be involved to port this code to use a hosted model eg via HF? 
I assume its not enough to have an embedding API?

alternatively could there be an installer that grabs the required files, to add to a docker container?

**Comment by jparkerweb** [comment]
I added a download-models tool that might help you get closer to your goal of pre-downloading/packaging the model files.
[https://github.com/jparkerweb/semantic-chunking?tab=readme-ov-file#-pre-downloading-models](https://github.com/jparkerweb/semantic-chunking?tab=readme-ov-file#-pre-downloading-models)

**Comment by davevilela** [comment]
@jparkerweb hey, could I run this on runpod or cloudflare workers AI?

**Comment by davevilela** [comment]
I'm trying to use this library in a cloudflare worker, and getting this error:

<img width="648" alt="Screenshot 2024-10-22 at 15 44 26" src="https://github.com/user-attachments/assets/37acd62d-e153-4bff-9cef-8243bd0ec51e">

Here's an overview of my setup:

![Screenshot 2024-10-22 at 15 43 05](https://github.com/user-attachments/assets/62eed990-dcb6-44f2-a611-35e3c3c58d04)

**Comment by dcsan** [comment]
not the author but would be surprised if it works in a worker - it needs to download a lot of model data first time its run.

**Comment by davevilela** [comment]
@dcsan Hey! What would you recommend to deploy this?

**Comment by davevilela** [comment]
@dcsan This error is occurring even after manually downloading the models locally. I have no clue on how to solve this.
